# # This is a basic workflow to help you get started with Actions

# name: PostgreSQL for GitHub Actions
# on:
# push:
#     branches: [ main ]
# pull_request:
#     branches: [ main ]
# jobs:
# build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - uses: azure/login@v1
#     with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
# - uses: azure/postgresql@v1
#   with:
#     server-name: jmm.postgres.database.azure.com
#     connection-string: ${{ secrets.AZURE_POSTGRESQL_CONNECTION_STRING }}
#     sql-file: './jmm.sql'
#     # Azure logout
# - name: logout
#   run: |
#      az logout
